#!/usr/bin/env bash
# reindex.sh — "grapify": local code/knowledge index so agents locate symbols & spec
# sections without reading whole files (saves tokens). Run after each completed task.
#
#   ./scripts/reindex.sh          # rebuild INDEX.md (+ .tags if universal-ctags present)
#
# Outputs:
#   docs/superpowers/INDEX.md  — committed heading/symbol map (file:line -> name)
#   .tags                      — ctags symbol DB (gitignored), if universal-ctags installed
#
# Portable: depends only on POSIX grep + git (no ripgrep/alias dependency).
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUT="docs/superpowers/INDEX.md"
ts="${REINDEX_TS:-$(date -u +%Y-%m-%dT%H:%MZ 2>/dev/null || echo unknown)}"

mkdir -p "$(dirname "$OUT")"
{
  echo "# VenuePro code/knowledge index (\"grapify\")"
  echo
  echo "_Generated by \`scripts/reindex.sh\` at $ts. Read this first to jump straight to a file:line instead of reading whole files. Rebuild after each task: \`./scripts/reindex.sh\`._"
  echo

  # --- Markdown heading map (the big token-saver while the repo is spec-heavy) ---
  echo "## Docs — heading map"
  echo
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    case "$f" in */INDEX.md) continue;; esac
    echo "### \`$f\`"
    grep -nE '^#{1,4} ' "$f" 2>/dev/null | sed -E 's/^([0-9]+):(#+) /- L\1 \2 /' || true
    echo
  done < <(git ls-files '*.md' | sort)

  # --- Code symbols (auto-activates once Laravel/PHP/JS is scaffolded) ---
  php_files=$(git ls-files '*.php' 2>/dev/null || true)
  if [ -n "$php_files" ]; then
    echo "## PHP — classes / functions"
    echo '```'
    echo "$php_files" | xargs grep -nE '^\s*(final |abstract )?(class|interface|trait|enum) \w+|^\s*(public|protected|private|static| )*function \w+' 2>/dev/null | head -2000 || true
    echo '```'; echo
    route_files=$(git ls-files 'routes/*.php' 2>/dev/null || true)
    if [ -n "$route_files" ]; then
      echo "## Routes"; echo '```'
      echo "$route_files" | xargs grep -nE 'Route::(get|post|put|patch|delete|resource|group)' 2>/dev/null || true
      echo '```'; echo
    fi
  fi
  js_files=$(git ls-files '*.js' '*.ts' 2>/dev/null || true)
  if [ -n "$js_files" ]; then
    echo "## JS/TS — exports / functions / classes"
    echo '```'
    echo "$js_files" | xargs grep -nE '^\s*export |^\s*(async )?function \w+|^\s*class \w+' 2>/dev/null | head -2000 || true
    echo '```'; echo
  fi
} > "$OUT"

# --- Optional universal-ctags symbol DB for jump-to-def (BSD /usr/bin/ctags is skipped) ---
if command -v ctags >/dev/null 2>&1 && ctags --version 2>/dev/null | grep -qi universal; then
  ctags -R --languages=PHP,JavaScript,TypeScript -f .tags \
    --exclude=vendor --exclude=node_modules --exclude=.git . 2>/dev/null \
    && echo "reindex: .tags rebuilt ($(wc -l < .tags 2>/dev/null | tr -d ' ') symbols)" \
    || echo "reindex: ctags run skipped"
else
  echo "reindex: universal-ctags not found (symbol DB skipped; INDEX.md still built). Install: brew install universal-ctags"
fi

echo "reindex: wrote $OUT"
